// The spine's order, in ONE place (cold read 6, 2026-09-28). The sidebar (components/Sidebar.astro)
// shelves the chronicle by Act; Starlight's prev/next walked its own autogenerated sidebar, which is
// in FILENAME order (`<date>-<stem>.md`, so date, then the stem alphabetically). The two agreed until
// three chapters shared 2026-08-13: `five-nights…` (Act 22) sorts before `the-firewall…` (Act 20),
// and a stranger followed Next from Act 18 to 22 and then back to 20 (cold read 6). Both now read
// the order from here, so they cannot drift apart again.
import { getCollection } from 'astro:content';

/** The chronicle: content/awakening/ -> /awakening/... */
export const CHRONICLE = '/awakening/';

export interface SpineKeys {
  act: Map<string, number | undefined>;
  date: Map<string, number>;
}

/** Act and date for every doc, keyed by the sidebar's href form (`/<id>/`). */
export async function spineKeys(): Promise<SpineKeys> {
  const act = new Map<string, number | undefined>();
  const date = new Map<string, number>();
  for (const d of await getCollection('docs')) {
    act.set(`/${d.id}/`, d.data.act);
    date.set(`/${d.id}/`, d.data.date ? new Date(d.data.date).getTime() : 0);
  }
  return { act, date };
}

/** Act, then date inside an Act (two threads of one night), then href so the order is total. */
export const bySpine = (k: SpineKeys) => (a: { href: string }, b: { href: string }) =>
  (k.act.get(a.href)! - k.act.get(b.href)!) || (k.date.get(a.href)! - k.date.get(b.href)!) || a.href.localeCompare(b.href);
